import React from "react";
import {useState} from "react";
import {CardMedia, Divider, Box, Typography, Button, Card, CardActionArea, CardActions, CardContent, AppBar, Container, Toolbar} from "@mui/material";
import '../top-songs/TopSongs.css'
import { textTransform } from "@mui/system";


let x = {
    "items": [
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0eDvMgVFoNV3TpwtrVCoTj"
              },
              "href": "https://api.spotify.com/v1/artists/0eDvMgVFoNV3TpwtrVCoTj",
              "id": "0eDvMgVFoNV3TpwtrVCoTj",
              "name": "Pop Smoke",
              "type": "artist",
              "uri": "spotify:artist:0eDvMgVFoNV3TpwtrVCoTj"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/2MDU46hcBn3u94s46BOSdv"
          },
          "href": "https://api.spotify.com/v1/albums/2MDU46hcBn3u94s46BOSdv",
          "id": "2MDU46hcBn3u94s46BOSdv",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27346e1307c35579c3483ea7b03",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0246e1307c35579c3483ea7b03",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485146e1307c35579c3483ea7b03",
              "width": 64
            }
          ],
          "name": "Shoot For The Stars Aim For The Moon (Deluxe)",
          "release_date": "2020-07-20",
          "release_date_precision": "day",
          "total_tracks": 34,
          "type": "album",
          "uri": "spotify:album:2MDU46hcBn3u94s46BOSdv"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/0eDvMgVFoNV3TpwtrVCoTj"
            },
            "href": "https://api.spotify.com/v1/artists/0eDvMgVFoNV3TpwtrVCoTj",
            "id": "0eDvMgVFoNV3TpwtrVCoTj",
            "name": "Pop Smoke",
            "type": "artist",
            "uri": "spotify:artist:0eDvMgVFoNV3TpwtrVCoTj"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/31W5EY0aAly4Qieq6OFu6I"
            },
            "href": "https://api.spotify.com/v1/artists/31W5EY0aAly4Qieq6OFu6I",
            "id": "31W5EY0aAly4Qieq6OFu6I",
            "name": "A Boogie Wit da Hoodie",
            "type": "artist",
            "uri": "spotify:artist:31W5EY0aAly4Qieq6OFu6I"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 190534,
        "explicit": true,
        "external_ids": {
          "isrc": "USUM72014370"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/2r6OAV3WsYtXuXjvJ1lIDi"
        },
        "href": "https://api.spotify.com/v1/tracks/2r6OAV3WsYtXuXjvJ1lIDi",
        "id": "2r6OAV3WsYtXuXjvJ1lIDi",
        "is_local": false,
        "name": "Hello (feat. A Boogie Wit da Hoodie)",
        "popularity": 78,
        "preview_url": "https://p.scdn.co/mp3-preview/dff3697d38fe2313aa2d3c594039377bfd520c04?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 30,
        "type": "track",
        "uri": "spotify:track:2r6OAV3WsYtXuXjvJ1lIDi"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4O15NlyKLIASxsJ0PrXPfz"
              },
              "href": "https://api.spotify.com/v1/artists/4O15NlyKLIASxsJ0PrXPfz",
              "id": "4O15NlyKLIASxsJ0PrXPfz",
              "name": "Lil Uzi Vert",
              "type": "artist",
              "uri": "spotify:artist:4O15NlyKLIASxsJ0PrXPfz"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/7IyoGB8J31fvQDwGtHAq9m"
          },
          "href": "https://api.spotify.com/v1/albums/7IyoGB8J31fvQDwGtHAq9m",
          "id": "7IyoGB8J31fvQDwGtHAq9m",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273d5f1bbe527fa685633339add",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02d5f1bbe527fa685633339add",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851d5f1bbe527fa685633339add",
              "width": 64
            }
          ],
          "name": "Eternal Atake",
          "release_date": "2020-03-06",
          "release_date_precision": "day",
          "total_tracks": 18,
          "type": "album",
          "uri": "spotify:album:7IyoGB8J31fvQDwGtHAq9m"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4O15NlyKLIASxsJ0PrXPfz"
            },
            "href": "https://api.spotify.com/v1/artists/4O15NlyKLIASxsJ0PrXPfz",
            "id": "4O15NlyKLIASxsJ0PrXPfz",
            "name": "Lil Uzi Vert",
            "type": "artist",
            "uri": "spotify:artist:4O15NlyKLIASxsJ0PrXPfz"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 234626,
        "explicit": true,
        "external_ids": {
          "isrc": "USAT22001369"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/3kW4z2pIj5VY5fLjBrMRL5"
        },
        "href": "https://api.spotify.com/v1/tracks/3kW4z2pIj5VY5fLjBrMRL5",
        "id": "3kW4z2pIj5VY5fLjBrMRL5",
        "is_local": false,
        "name": "P2",
        "popularity": 69,
        "preview_url": "https://p.scdn.co/mp3-preview/5bcd2589c175e0809500fbbfd0879f77c88a2e86?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 16,
        "type": "track",
        "uri": "spotify:track:3kW4z2pIj5VY5fLjBrMRL5"
      },
      {
        "album": {
          "album_type": "SINGLE",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6JvU33PZ8MtZyeFTESr09O"
              },
              "href": "https://api.spotify.com/v1/artists/6JvU33PZ8MtZyeFTESr09O",
              "id": "6JvU33PZ8MtZyeFTESr09O",
              "name": "Kap G",
              "type": "artist",
              "uri": "spotify:artist:6JvU33PZ8MtZyeFTESr09O"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4X4eIXh8tgQPiwxkxsp5lz"
          },
          "href": "https://api.spotify.com/v1/albums/4X4eIXh8tgQPiwxkxsp5lz",
          "id": "4X4eIXh8tgQPiwxkxsp5lz",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2730cf8cef532d5bd20c7fc387f",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e020cf8cef532d5bd20c7fc387f",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048510cf8cef532d5bd20c7fc387f",
              "width": 64
            }
          ],
          "name": "Mood",
          "release_date": "2017-11-17",
          "release_date_precision": "day",
          "total_tracks": 3,
          "type": "album",
          "uri": "spotify:album:4X4eIXh8tgQPiwxkxsp5lz"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/6JvU33PZ8MtZyeFTESr09O"
            },
            "href": "https://api.spotify.com/v1/artists/6JvU33PZ8MtZyeFTESr09O",
            "id": "6JvU33PZ8MtZyeFTESr09O",
            "name": "Kap G",
            "type": "artist",
            "uri": "spotify:artist:6JvU33PZ8MtZyeFTESr09O"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4O15NlyKLIASxsJ0PrXPfz"
            },
            "href": "https://api.spotify.com/v1/artists/4O15NlyKLIASxsJ0PrXPfz",
            "id": "4O15NlyKLIASxsJ0PrXPfz",
            "name": "Lil Uzi Vert",
            "type": "artist",
            "uri": "spotify:artist:4O15NlyKLIASxsJ0PrXPfz"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2hlmm7s2ICUX0LVIhVFlZQ"
            },
            "href": "https://api.spotify.com/v1/artists/2hlmm7s2ICUX0LVIhVFlZQ",
            "id": "2hlmm7s2ICUX0LVIhVFlZQ",
            "name": "Gunna",
            "type": "artist",
            "uri": "spotify:artist:2hlmm7s2ICUX0LVIhVFlZQ"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 223920,
        "explicit": true,
        "external_ids": {
          "isrc": "USAT21704529"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/4kfEy7h6bWBS5OaDpccTap"
        },
        "href": "https://api.spotify.com/v1/tracks/4kfEy7h6bWBS5OaDpccTap",
        "id": "4kfEy7h6bWBS5OaDpccTap",
        "is_local": false,
        "name": "Marvelous Day (feat. Lil Uzi Vert & Gunna)",
        "popularity": 55,
        "preview_url": "https://p.scdn.co/mp3-preview/e237fab45720bbe4dd68bd594bf488c8d3b8d5d5?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 2,
        "type": "track",
        "uri": "spotify:track:4kfEy7h6bWBS5OaDpccTap"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0H39MdGGX6dbnnQPt6NQkZ"
              },
              "href": "https://api.spotify.com/v1/artists/0H39MdGGX6dbnnQPt6NQkZ",
              "id": "0H39MdGGX6dbnnQPt6NQkZ",
              "name": "SAINt JHN",
              "type": "artist",
              "uri": "spotify:artist:0H39MdGGX6dbnnQPt6NQkZ"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/0ufGvePLRPce9olVIZhRyE"
          },
          "href": "https://api.spotify.com/v1/albums/0ufGvePLRPce9olVIZhRyE",
          "id": "0ufGvePLRPce9olVIZhRyE",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273cdb624d3049740537b9f7b50",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02cdb624d3049740537b9f7b50",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851cdb624d3049740537b9f7b50",
              "width": 64
            }
          ],
          "name": "Ghetto Lenny's Love Songs",
          "release_date": "2019-08-23",
          "release_date_precision": "day",
          "total_tracks": 14,
          "type": "album",
          "uri": "spotify:album:0ufGvePLRPce9olVIZhRyE"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/0H39MdGGX6dbnnQPt6NQkZ"
            },
            "href": "https://api.spotify.com/v1/artists/0H39MdGGX6dbnnQPt6NQkZ",
            "id": "0H39MdGGX6dbnnQPt6NQkZ",
            "name": "SAINt JHN",
            "type": "artist",
            "uri": "spotify:artist:0H39MdGGX6dbnnQPt6NQkZ"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 169405,
        "explicit": true,
        "external_ids": {
          "isrc": "USUYG1268277"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/691df0fYjhhszUgQH3FGvP"
        },
        "href": "https://api.spotify.com/v1/tracks/691df0fYjhhszUgQH3FGvP",
        "id": "691df0fYjhhszUgQH3FGvP",
        "is_local": false,
        "name": "94 Bentley",
        "popularity": 59,
        "preview_url": "https://p.scdn.co/mp3-preview/3a0d9e4fd71eb40247d08e56cf9c819423c32922?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 6,
        "type": "track",
        "uri": "spotify:track:691df0fYjhhszUgQH3FGvP"
      },
      {
        "album": {
          "album_type": "SINGLE",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/28yVvEvA2lT3K5RNIhV1Dj"
              },
              "href": "https://api.spotify.com/v1/artists/28yVvEvA2lT3K5RNIhV1Dj",
              "id": "28yVvEvA2lT3K5RNIhV1Dj",
              "name": "BAYNK",
              "type": "artist",
              "uri": "spotify:artist:28yVvEvA2lT3K5RNIhV1Dj"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/5hb9aZmt8McCp8ktZh2dJZ"
          },
          "href": "https://api.spotify.com/v1/albums/5hb9aZmt8McCp8ktZh2dJZ",
          "id": "5hb9aZmt8McCp8ktZh2dJZ",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2733f863eb5ebcf1655dd4472eb",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e023f863eb5ebcf1655dd4472eb",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048513f863eb5ebcf1655dd4472eb",
              "width": 64
            }
          ],
          "name": "Someone's EP II",
          "release_date": "2019-05-22",
          "release_date_precision": "day",
          "total_tracks": 7,
          "type": "album",
          "uri": "spotify:album:5hb9aZmt8McCp8ktZh2dJZ"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/28yVvEvA2lT3K5RNIhV1Dj"
            },
            "href": "https://api.spotify.com/v1/artists/28yVvEvA2lT3K5RNIhV1Dj",
            "id": "28yVvEvA2lT3K5RNIhV1Dj",
            "name": "BAYNK",
            "type": "artist",
            "uri": "spotify:artist:28yVvEvA2lT3K5RNIhV1Dj"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 231192,
        "explicit": false,
        "external_ids": {
          "isrc": "GB45A1901541"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/4PdLup4OaCGktZG8cvbkBz"
        },
        "href": "https://api.spotify.com/v1/tracks/4PdLup4OaCGktZG8cvbkBz",
        "id": "4PdLup4OaCGktZG8cvbkBz",
        "is_local": false,
        "name": "go with u",
        "popularity": 65,
        "preview_url": "https://p.scdn.co/mp3-preview/a7d937a10c30879f754a95a2d5e56def2d7caa9e?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 3,
        "type": "track",
        "uri": "spotify:track:4PdLup4OaCGktZG8cvbkBz"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/20sxb77xiYeusSH8cVdatc"
              },
              "href": "https://api.spotify.com/v1/artists/20sxb77xiYeusSH8cVdatc",
              "id": "20sxb77xiYeusSH8cVdatc",
              "name": "Meek Mill",
              "type": "artist",
              "uri": "spotify:artist:20sxb77xiYeusSH8cVdatc"
            }
          ],
          "available_markets": [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/0zhZDmHEtDtok393SbZ3d7"
          },
          "href": "https://api.spotify.com/v1/albums/0zhZDmHEtDtok393SbZ3d7",
          "id": "0zhZDmHEtDtok393SbZ3d7",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273f0c746d1b52c883c19b25a51",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02f0c746d1b52c883c19b25a51",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851f0c746d1b52c883c19b25a51",
              "width": 64
            }
          ],
          "name": "Dreams and Nightmares (Deluxe Edition)",
          "release_date": "2012-10-26",
          "release_date_precision": "day",
          "total_tracks": 16,
          "type": "album",
          "uri": "spotify:album:0zhZDmHEtDtok393SbZ3d7"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/20sxb77xiYeusSH8cVdatc"
            },
            "href": "https://api.spotify.com/v1/artists/20sxb77xiYeusSH8cVdatc",
            "id": "20sxb77xiYeusSH8cVdatc",
            "name": "Meek Mill",
            "type": "artist",
            "uri": "spotify:artist:20sxb77xiYeusSH8cVdatc"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4"
            },
            "href": "https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4",
            "id": "3TVXtAsR1Inumwj472S9r4",
            "name": "Drake",
            "type": "artist",
            "uri": "spotify:artist:3TVXtAsR1Inumwj472S9r4"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 289706,
        "explicit": true,
        "external_ids": {
          "isrc": "USWB11201519"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/32UIpKdyGzgTPTO8e5ge5c"
        },
        "href": "https://api.spotify.com/v1/tracks/32UIpKdyGzgTPTO8e5ge5c",
        "id": "32UIpKdyGzgTPTO8e5ge5c",
        "is_local": false,
        "name": "Amen (feat. Drake)",
        "popularity": 50,
        "preview_url": "https://p.scdn.co/mp3-preview/0699c77f553ceb465e1a30b0db2ada4710709ab9?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 7,
        "type": "track",
        "uri": "spotify:track:32UIpKdyGzgTPTO8e5ge5c"
      },
      {
        "album": {
          "album_type": "SINGLE",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/7rkW85dBwwrJtlHRDkJDAC"
              },
              "href": "https://api.spotify.com/v1/artists/7rkW85dBwwrJtlHRDkJDAC",
              "id": "7rkW85dBwwrJtlHRDkJDAC",
              "name": "NAV",
              "type": "artist",
              "uri": "spotify:artist:7rkW85dBwwrJtlHRDkJDAC"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/3ZpAmjvMEsr7rsiTUbSS0W"
          },
          "href": "https://api.spotify.com/v1/albums/3ZpAmjvMEsr7rsiTUbSS0W",
          "id": "3ZpAmjvMEsr7rsiTUbSS0W",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2733c35fead2037a32b78cbbddf",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e023c35fead2037a32b78cbbddf",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048513c35fead2037a32b78cbbddf",
              "width": 64
            }
          ],
          "name": "Wanted You (feat. Lil Uzi Vert)",
          "release_date": "2017-11-03",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:3ZpAmjvMEsr7rsiTUbSS0W"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/7rkW85dBwwrJtlHRDkJDAC"
            },
            "href": "https://api.spotify.com/v1/artists/7rkW85dBwwrJtlHRDkJDAC",
            "id": "7rkW85dBwwrJtlHRDkJDAC",
            "name": "NAV",
            "type": "artist",
            "uri": "spotify:artist:7rkW85dBwwrJtlHRDkJDAC"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4O15NlyKLIASxsJ0PrXPfz"
            },
            "href": "https://api.spotify.com/v1/artists/4O15NlyKLIASxsJ0PrXPfz",
            "id": "4O15NlyKLIASxsJ0PrXPfz",
            "name": "Lil Uzi Vert",
            "type": "artist",
            "uri": "spotify:artist:4O15NlyKLIASxsJ0PrXPfz"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 228080,
        "explicit": true,
        "external_ids": {
          "isrc": "USUG11702054"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/790MhTXPFrYkrqCKvpg4t1"
        },
        "href": "https://api.spotify.com/v1/tracks/790MhTXPFrYkrqCKvpg4t1",
        "id": "790MhTXPFrYkrqCKvpg4t1",
        "is_local": false,
        "name": "Wanted You (feat. Lil Uzi Vert)",
        "popularity": 54,
        "preview_url": "https://p.scdn.co/mp3-preview/2466ab29f90d927256b9d60d91dbec7d8f72d377?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:790MhTXPFrYkrqCKvpg4t1"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1Bl6wpkWCQ4KVgnASpvzzA"
              },
              "href": "https://api.spotify.com/v1/artists/1Bl6wpkWCQ4KVgnASpvzzA",
              "id": "1Bl6wpkWCQ4KVgnASpvzzA",
              "name": "BROCKHAMPTON",
              "type": "artist",
              "uri": "spotify:artist:1Bl6wpkWCQ4KVgnASpvzzA"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/0XnqQzdSFAml08XZoRt1St"
          },
          "href": "https://api.spotify.com/v1/albums/0XnqQzdSFAml08XZoRt1St",
          "id": "0XnqQzdSFAml08XZoRt1St",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2737d15fb20303a589acc1ab98b",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e027d15fb20303a589acc1ab98b",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048517d15fb20303a589acc1ab98b",
              "width": 64
            }
          ],
          "name": "SATURATION II",
          "release_date": "2017-08-25",
          "release_date_precision": "day",
          "total_tracks": 16,
          "type": "album",
          "uri": "spotify:album:0XnqQzdSFAml08XZoRt1St"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1Bl6wpkWCQ4KVgnASpvzzA"
            },
            "href": "https://api.spotify.com/v1/artists/1Bl6wpkWCQ4KVgnASpvzzA",
            "id": "1Bl6wpkWCQ4KVgnASpvzzA",
            "name": "BROCKHAMPTON",
            "type": "artist",
            "uri": "spotify:artist:1Bl6wpkWCQ4KVgnASpvzzA"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 261000,
        "explicit": true,
        "external_ids": {
          "isrc": "USUYG1156283"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/42tBlHWL3VfDkUM2iWcc5p"
        },
        "href": "https://api.spotify.com/v1/tracks/42tBlHWL3VfDkUM2iWcc5p",
        "id": "42tBlHWL3VfDkUM2iWcc5p",
        "is_local": false,
        "name": "GUMMY",
        "popularity": 56,
        "preview_url": "https://p.scdn.co/mp3-preview/3064f606f4ca9554ea4850090d9daa6d876fc8c9?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:42tBlHWL3VfDkUM2iWcc5p"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0QHgL1lAIqAw0HtD7YldmP"
              },
              "href": "https://api.spotify.com/v1/artists/0QHgL1lAIqAw0HtD7YldmP",
              "id": "0QHgL1lAIqAw0HtD7YldmP",
              "name": "DJ Khaled",
              "type": "artist",
              "uri": "spotify:artist:0QHgL1lAIqAw0HtD7YldmP"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/7FyxsUO4kVqRfo2ne1aUOg"
          },
          "href": "https://api.spotify.com/v1/albums/7FyxsUO4kVqRfo2ne1aUOg",
          "id": "7FyxsUO4kVqRfo2ne1aUOg",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273dd87a2f68949c8fcbbec91be",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02dd87a2f68949c8fcbbec91be",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851dd87a2f68949c8fcbbec91be",
              "width": 64
            }
          ],
          "name": "We The Best Forever",
          "release_date": "2011-01-01",
          "release_date_precision": "day",
          "total_tracks": 12,
          "type": "album",
          "uri": "spotify:album:7FyxsUO4kVqRfo2ne1aUOg"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/0QHgL1lAIqAw0HtD7YldmP"
            },
            "href": "https://api.spotify.com/v1/artists/0QHgL1lAIqAw0HtD7YldmP",
            "id": "0QHgL1lAIqAw0HtD7YldmP",
            "name": "DJ Khaled",
            "type": "artist",
            "uri": "spotify:artist:0QHgL1lAIqAw0HtD7YldmP"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4"
            },
            "href": "https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4",
            "id": "3TVXtAsR1Inumwj472S9r4",
            "name": "Drake",
            "type": "artist",
            "uri": "spotify:artist:3TVXtAsR1Inumwj472S9r4"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1sBkRIssrMs1AbVkOJbc7a"
            },
            "href": "https://api.spotify.com/v1/artists/1sBkRIssrMs1AbVkOJbc7a",
            "id": "1sBkRIssrMs1AbVkOJbc7a",
            "name": "Rick Ross",
            "type": "artist",
            "uri": "spotify:artist:1sBkRIssrMs1AbVkOJbc7a"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/55Aa2cqylxrFIXC767Z865"
            },
            "href": "https://api.spotify.com/v1/artists/55Aa2cqylxrFIXC767Z865",
            "id": "55Aa2cqylxrFIXC767Z865",
            "name": "Lil Wayne",
            "type": "artist",
            "uri": "spotify:artist:55Aa2cqylxrFIXC767Z865"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 296146,
        "explicit": true,
        "external_ids": {
          "isrc": "USCM51100126"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/608a1wIsSd5KzMEqm1O7w3"
        },
        "href": "https://api.spotify.com/v1/tracks/608a1wIsSd5KzMEqm1O7w3",
        "id": "608a1wIsSd5KzMEqm1O7w3",
        "is_local": false,
        "name": "I'm On One",
        "popularity": 69,
        "preview_url": "https://p.scdn.co/mp3-preview/1c8ab63196181d7bd63b1700c462e399e5945514?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:608a1wIsSd5KzMEqm1O7w3"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4O15NlyKLIASxsJ0PrXPfz"
              },
              "href": "https://api.spotify.com/v1/artists/4O15NlyKLIASxsJ0PrXPfz",
              "id": "4O15NlyKLIASxsJ0PrXPfz",
              "name": "Lil Uzi Vert",
              "type": "artist",
              "uri": "spotify:artist:4O15NlyKLIASxsJ0PrXPfz"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/7IyoGB8J31fvQDwGtHAq9m"
          },
          "href": "https://api.spotify.com/v1/albums/7IyoGB8J31fvQDwGtHAq9m",
          "id": "7IyoGB8J31fvQDwGtHAq9m",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273d5f1bbe527fa685633339add",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02d5f1bbe527fa685633339add",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851d5f1bbe527fa685633339add",
              "width": 64
            }
          ],
          "name": "Eternal Atake",
          "release_date": "2020-03-06",
          "release_date_precision": "day",
          "total_tracks": 18,
          "type": "album",
          "uri": "spotify:album:7IyoGB8J31fvQDwGtHAq9m"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4O15NlyKLIASxsJ0PrXPfz"
            },
            "href": "https://api.spotify.com/v1/artists/4O15NlyKLIASxsJ0PrXPfz",
            "id": "4O15NlyKLIASxsJ0PrXPfz",
            "name": "Lil Uzi Vert",
            "type": "artist",
            "uri": "spotify:artist:4O15NlyKLIASxsJ0PrXPfz"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 210261,
        "explicit": true,
        "external_ids": {
          "isrc": "USAT22001354"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/7hav1MHURQf5SAoPk0egqh"
        },
        "href": "https://api.spotify.com/v1/tracks/7hav1MHURQf5SAoPk0egqh",
        "id": "7hav1MHURQf5SAoPk0egqh",
        "is_local": false,
        "name": "Baby Pluto",
        "popularity": 66,
        "preview_url": "https://p.scdn.co/mp3-preview/f1f785d2ad5520f521564a208fc477b2edf62b8c?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:7hav1MHURQf5SAoPk0egqh"
      }
    ],
    "total": 50,
    "limit": 10,
    "offset": 5,
    "href": "https://api.spotify.com/v1/me/top/tracks?limit=10&offset=5",
    "previous": null,
    "next": "https://api.spotify.com/v1/me/top/tracks?limit=10&offset=15"
  }
function TopSongs(props) {
    const user = "Ashwin Shankar"
    const[songsData, setSongsData] = useState(x.items)

    const buttonStyle = {
        padding: '5px', 
        paddingInline: '50px',
        flex: .4,
    }
    return (
        <div>
            <Toolbar variant='dense' style={{padding: '0px', minHeight: '80px' }}>
                <Container maxWidth='2000px' style={{padding: 'none', display: "flex",}}>
                <Typography style={{textAlign: "center", padding: '10px', flex: 0.6, fontWeight: 'bold', color: "rgb(30,215,96)", letterSpacing: '4px'}}variant='h4'>{user}'s<br></br> Top Songs</Typography>
                <Button size='medium'  style={buttonStyle} variant='text'>
                <Typography color ='black' variant='h5'>
                                            All Time
                                        </Typography>
                    </Button>
                <Button size='small' variant='text' style={buttonStyle}>
                <Typography color ='black' variant='h5'>
                                            Last Year
                                        </Typography>
                </Button>
                <Button size='small' style={buttonStyle} variant='text' >
                <Typography color ='black' variant='h5'>
                                            Last Month
                                        </Typography>
                </Button>
                </Container>
            </Toolbar>
            <Divider ></Divider>
            <Container maxWidth='false' sx={{m: 2}} style={{ padding: '0px', overflow: 'auto'}}>
            {songsData.map((song) =>  (
                <div onClick={() => (
                    window.open(song.external_urls.spotify)
                )}>
                <Card variant="elevation" sx={{m: 1.8}} style={{width: '325px', height: '325px', float: 'left' , padding: '10px', backgroundColor: "SlateGrey", boxShadow: "0 12px 20px rgba(0,0,0,0.3)",
                "&:hover": {
                  boxShadow: "0 16px 70px -12.125px rgba(0,0,0,0.3)"}}}>
                      <CardContent>
                          <CardMedia
                          component="img"
                          height='240'
                          width='200'
                          image={song.album.images[1].url}
                          alt='Album Cover Not Found'

                          />
                      <Typography    sx={{ overflow: 'hidden', textOverflow: 'ellipsis', display: '-webkit-box', WebkitLineClamp: '1', WebkitBoxOrient: 'vertical', }}
   display='inline' variant='h5'style={{fontWeight: 'bold', }}>{song.album.name}</Typography>
                    <Typography variant ='h6'>{song.album.artists[0].name}</Typography>     
                    </CardContent>   
                </Card>
                </div>
            ))}
            </Container>
        </div>
    )



}

export default TopSongs;